version: '3.2'


services:

  tests:
    image: vfarcic/docker-flow-swarm-listener-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docs:
    image: cilerler/mkdocs
    volumes:
      - .:/docs
    command: bash -c "pip install pygments && pip install pymdown-extensions && mkdocs build"
